function s=innerloop_feedback(s,e)
assert(strcmp(s.phase,'read'),'landing:Order','Feedback already written; advance before next feedback');
assert(isfield(s,'observed_timestamp') && abs(s.observed_timestamp-s.timestamp)<1e-8, ...
    'landing:Order','Read current sensor truth before writing feedback');
if isfield(s.config,'reference_camera_id')
    assert(isfield(e,'diagnostics') && isfield(e.diagnostics,'reference_camera_id') && ...
        strcmp(e.diagnostics.reference_camera_id,s.config.reference_camera_id), ...
        'landing:Reference','Navigation feedback must use the fixed reference camera');
end
s.estimate=e;
o=innerloop_evaluate(s);
s.feedback=struct('timestamp',s.timestamp, ...
    'gear_relative_ned_m',o.gear_relative_estimate_ned, ...
    'distance_m',o.relative_distance_estimate_m, ...
    'covariance_ned',o.relative_covariance_ned,'valid',logical(o.feedback_valid));
s.phase='feedback';
end
